from grams.core.table import LinkedTable

class GramsDB:
    @staticmethod
    def init(datadir: str) -> None: ...
    @staticmethod
    def get_instance() -> GramsDB: ...
    def get_algo_context(self, table: LinkedTable, n_hop: int) -> AlgoContext: ...

class AlgoContext: ...
